CREATE TABLE IF NOT EXISTS UserContact (	
	email CHAR(50) PRIMARY KEY,
	phone CHAR(20)
);

CREATE TABLE IF NOT EXISTS UserInfo (
	id INTEGER PRIMARY KEY,
	email VARCHAR(50) NOT NULL UNIQUE,
	name VARCHAR(50),
	FOREIGN KEY(email)
		REFERENCES UserContact
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Follows (
	uid INTEGER,
	followed_id INTEGER,
	follower_id INTEGER,
	PRIMARY KEY(uid, followed_id, follower_id),
	FOREIGN KEY(uid)
		REFERENCES UserInfo
		ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS VideoMedia (
	name VARCHAR(50),
	PRIMARY KEY(name)
);

CREATE TABLE IF NOT EXISTS Series (
	name VARCHAR(50),
	seasons INTEGER,
	episodes INTEGER,
	PRIMARY KEY(name),
	FOREIGN KEY(name)
		REFERENCES VideoMedia
		ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Movies (
	name VARCHAR(50),
	length INTEGER,
	PRIMARY KEY(name),
	FOREIGN KEY(name)
		REFERENCES VideoMedia
		ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS MoviePeople (
	name VARCHAR(50),
	id INTEGER,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Country (
	name VARCHAR(50),
	id INTEGER UNIQUE,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Lists (
	id INTEGER,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS CuratedList (
	id Integer UNIQUE NOT NULL,
	curator VARCHAR(50),
	name CHAR(50),
	PRIMARY KEY(id,curator)
);